# kubernetes/github-auth-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secrets
  namespace: backstage
type: Opaque
data:
  AUTH_GITHUB_CLIENT_ID: 'T3YyM2xpZlVKaElDQVdkeUlCNEw=' # base 64
  AUTH_GITHUB_CLIENT_SECRET: 'M2VlZjk3NTRjNTY5ODQyODMzNGZmNTk0MTYxOTQ3ZTY2NjUyNzUxZQ==' # base 64
                             